# Generated by Django 5.1.3 on 2024-12-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman_utama', '0003_alter_userprofile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
