# Generated by Django 5.1.3 on 2024-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_payment_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('Gopay', 'Gopay'), ('QRIS', 'QRIS'), ('Dana', 'Dana')], max_length=50),
        ),
    ]
