# Generated by Django 5.1.3 on 2024-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='check_out_date',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('payed', 'Payed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'Dipesan'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='booked', max_length=10),
        ),
    ]
